apiVersion: v1
kind: Service
metadata:
  name: image-enhancement-api
  namespace: image-enhancement
spec:
  selector:
    app: image-enhancement-api
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP