apiVersion: v1
kind: Service
metadata:
  name: image-enhancement-frontend
  namespace: image-enhancement
spec:
  selector:
    app: image-enhancement-frontend
  ports:
  - port: 8501
    targetPort: 8501
  type: ClusterIP